title: "Adriel Tech"
author:
  name: Adriel Tech
description: "This is my FreeBSD, Linux and general IT guide dumping ground. Windows guides and tech rants might find there way here also!"

remote_theme: jekyll/minima
plugins:
- jekyll-feed
- jekyll-remote-theme
- jekyll-seo-tag

minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/adriel-tech" }

header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md
  - _pages/contact.md

show_excerpts: true

include:
  - _pages

exclude: 
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
