title: "Adriel's Speakeasy"
author:
  name: Adriel
description: "FreeBSD and other IT guides."

remote_theme: jekyll/minima
plugins:
- jekyll-feed
- jekyll-remote-theme
- jekyll-seo-tag

minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/adriel-tech" }

header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

show_excerpts: true

include:
  - _pages

exclude: 
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
